version: "3"
services:
  fight-club:
    build: ./
    ports:
      - 80:3000
    networks:
      - demo
    container_name: demo
    environment:
      NODE_ENV: docker
      GAME_SERVER_OPTS_SERVER_TYPE: gamemaster,damagecontroller
      GAME_DAMAGE_CONTROLLER_PROTOCOL: http
      GAME_DAMAGE_CONTROLLER_HOST: localhost
      GAME_DAMAGE_CONTROLLER_PORT: 4000,
      SERVER_PORT: 3000
    depends_on:
      - redis
      - mongo
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    ports:
      - 6379
    networks:
      - demo
    container_name: redis
    deploy:
      restart_policy:
        condition: on-failure


  mongo:
    image: mongo:latest
    ports:
      - 27017
    networks:
      - demo
    container_name: mongo
    deploy:
      restart_policy:
        condition: on-failure


networks:
  demo:

